### PR TITLE
Fix predict_type bug in xgboost

### LINKED ISSUE #52: classif.xgboost predicts probabilities even when predict_type is response
The same problem as #50

### PR DESCRIPTION
**Pull request by be-marc**
Closes #52

### CODE REVIEW

File: R/LearnerClassifXgboost.R [hunk 1]
```diff
@@ -145,7 +145,15 @@ LearnerClassifXgboost = R6Class("LearnerClassifXgboost", inherit = LearnerClassi
         }
       }
 
-      PredictionClassif$new(task = task, response = response, prob = prob)
+      if(!is.null(response)) {
+        PredictionClassif$new(task = task, response = response)
+      } else if(self$predict_type == "response") {
```
Comment (pat-s) [inline R/LearnerClassifXgboost.R]:
```suggestion
      } else if (self$predict_type == "response") {
```

File: R/LearnerClassifXgboost.R [hunk 2]
```diff
@@ -145,7 +145,15 @@ LearnerClassifXgboost = R6Class("LearnerClassifXgboost", inherit = LearnerClassi
         }
       }
 
-      PredictionClassif$new(task = task, response = response, prob = prob)
+      if(!is.null(response)) {
```
Comment (pat-s) [inline R/LearnerClassifXgboost.R]:
```suggestion
      if (!is.null(response)) {
```
